### ISSUE TITLE
Translate from portuguese to English

### ISSUE THREAD

**Issue by shadow44g4** [shadow44g4/o_que_voce_faria#1]
Hey

i need help translating from portuguese to english the src/oqvf_EN_US.java

Thanks

**Comment by anabastos** [comment]
I can do it :)

**Comment by shadow44g4** [comment]
Thanks Ana!  😁

**Comment by andreybleme** [comment]
@shadow44g4 I didn't notice that @anabastos was working on it and just submited a PR :100: 

:link:  [See the PR here](https://github.com/shadow44g4/o_que_voce_faria/pull/6)

**Comment by shadow44g4** [comment]
Thank you @andreybleme 

P.s: Estarei adicionando seu nome aos créditos do jogo! 😁
